### ISSUE TITLE
Improve diff view for table

### ISSUE THREAD

**Issue by arai-a** [arai-a/ecma262-compare#59]
testcase: https://arai-a.github.io/ecma262-compare/?pr=1896&collapsed=1
ins/del wraps tr/td, that breaks the layout.
I'm not sure what the best markup is tho...

**Comment by CYBAI** [comment]
While accessing https://arai-a.github.io/ecma262-compare/?pr=1896&collapsed=1, it says PR 1896 is not found 👀

**Comment by arai-a** [comment]
thanks. I performed GC last month and closed PR pages are removed.

here's the merged commit:
https://arai-a.github.io/ecma262-compare/?rev=e1c717927b7018c2e2f346b21c517d988f3c12c7&collapsed=1

**Comment by CYBAI** [comment]
I tried to play with the page and wonder how about handling specifically for tables?

when we meet a diff for tds, then we add `htmldiff-ins` (and `htmldiff-del`) class to `td` and not adding the `ins` and `del` element inside tables; also, I think the `htmldiff-change` is for adding the bottom border which might not needed for td diffs?

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/6782666/92391755-2cd82400-f158-11ea-88ac-c29e570e62fb.png">


WDYT?

**Comment by arai-a** [comment]
Thank you for the suggestion :)
yeah, I tried that locally and it looks perfect.

`htmldiff-change` is mostly for navigation with up/down arrow at the top-right of the page.
the underline is added by `<ins>`.  I'll apply `border: none` to such `<ins>`.
