### ISSUE TITLE
Tool only showing diff for the first commit in a PR

### ISSUE THREAD

**Issue by mathiasbynens** [arai-a/ecma262-compare#74]
https://arai-a.github.io/ecma262-compare/?pr=2418 only shows the first commit from PR https://github.com/tc39/ecma262/pull/2418, but there are many more commits in there. How can we get those changes to show up? Do we have to squash all commits into one, or is there a better way?

I’ve noticed that snapshots for the other commits exist, e.g. https://github.com/arai-a/ecma262-compare/commit/3af43c465efafde8b439ba2ad64735397a93d72c#diff-e0470c3d0ced583fef48857eb57c1bf942f16ba08479f02a10d7ec716ef2a509

**Comment by arai-a** [comment]
Thank you for reporting.

this is again due to disk space limit https://github.com/arai-a/ecma262-compare/issues/65
that updates from Nov 11 weren't reflected to the web: https://github.com/arai-a/ecma262-compare/commits/gh-pages

**Comment by arai-a** [comment]
Fixed by https://github.com/arai-a/ecma262-compare/commit/8431db5cf4cc37c4314b7b889fee9c65e0d7da5f , removing some unused revisions.

**Comment by mathiasbynens** [comment]
Thanks for the quick fix!
