### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dontcallmedom** [arai-a/ecma262-compare#86]
I would be interested to re-use and adapt the [htmldiff implementation](https://github.com/arai-a/ecma262-compare/blob/gh-pages/js/compare.js) in the context of W3C specs; to understand if I can do so, it would be helpful to have the license of the said code documented.

In any case, thanks a bunch for the great code!

**Comment by arai-a** [comment]
Thank you for the suggestion.

I've added LICENSE files.  The code is mainly MPLv2, given a part of code is based on mozilla-central.
Some imported files have separate licenses.

Let me know if you find any problems.

**Comment by dontcallmedom** [comment]
Many thanks!
